base_url: http://grokpodcast.com
podcast_file_storage: http://s3.amazonaws.com/grokpodcast/
google_analytics_code: UA-18562844-1
server:     true
watch:      true
permalink:  pretty
markdown:   rdiscount
exclude: ['bin', 'Rakefile', 'README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', 'config.rb', 'vendor']
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed

featured:
  title: Trabalho Remoto

deploy:
  github_pages:
    target_repository: 'grokpodcast/site'
