base_url: http://new.grokpodcast.com
podcast_file_storage: http://s3.amazonaws.com/grokpodcast/
google_analytics_code: UA-18562844-1
server:     true
auto:       true
permalink:  pretty
markdown:   rdiscount
exclude: ['Rakefile', 'README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', 'config.rb']
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed

featured:
  title: Trabalho Remoto
